/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 28 03:39:12 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestMessageBuilder extends MessageBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void testL2a4a6a8a9a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage(")9zD");
      assertEquals("Hello )9zD", string0);
  }

  @Test(timeout = 4000)
  public void testL2a4a6a8a9a16a19_1()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("dE");
      assertEquals("Hello dE", string0);
  }

  @Test(timeout = 4000)
  public void testL2a4a6a7a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("");
      assertEquals("Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void testL2a4a6a8a10a14a16a19()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("MessageBuilder");
      assertEquals("Too long: MessageBuilder", string0);
  }

  @Test(timeout = 4000)
  public void testL2a4a6a16()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      // Undeclared exception!
      try { 
        messageBuilder0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
